name: Autobuild

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: Run build
        run: cd src && go build -o windows-build.exe .
        env:
          GOOS: windows
      - name: Packaging
        run: mkdir pack && mv static pack && mv windows-build.exe pack

      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: ${{ github.workspace }}/src/pack

